### ISSUE TITLE
Attempting to run the demo in a github action gives an error

### ISSUE THREAD

**Issue by mhoward-ivre** [debianmaster/actions-k3s#6]
```
name: k3s Testing
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'v0.9.1'
    - run: |
        kubectl get nodes
```
The result is The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?

Am I missing something?
